const User = require("../Models/UserModel");
const otp_generator = require("otp-generator");
const bcrypt = require("bcrypt");
const sendEmail = require("../Email service/Email");
const JWT = require("jsonwebtoken");
//!Register
const register = async (req, res) => {
  try {
    console.log(req.body);
    //? check if user already exists via email
    const isUserExisting = await User.findOne({ email: req.body.email });
    if (isUserExisting) {
      console.log(`User with this email ${req.body.email} already exists`);

      return res.status(404).json({
        message: `User with this email ${req.body.email} already exists`,
      });
    }
    //? creating verification token
    const VerificationToken = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });
    const expires = new Date();
    expires.setMinutes(expires.getMinutes() + 5); //* 5 minutes
    //? hashing password
    const hashedPw = await bcrypt.hash(req.body.password, 10);
    //? if user do not already exists, creating user
    const newUser = await User({
      email: req.body.email,
      username: req.body.username,
      password: hashedPw,
      VerificationToken: {
        token: VerificationToken,
        expires: expires,
      },
    });
    await newUser.save();

    //? send account verification email
    const emailBody = `<p>Please click on the link to verify your account <b>http://localhost:5000/api/v1/user/verify/${VerificationToken}</b></p>`;
    const subject = `Verification Email`;
    await sendEmail(req.body.email, subject, emailBody);
    await res.status(201).json({
      message:
        "Signed In Successfully! A verification Email Have Been Sent To You.",
    });
  } catch (error) {
    res.json({ error });
  }
};
//! login
const login = async (req, res) => {
  try {
    //? get the payload
    const { email, password } = req.body;
    console.log(req.body);
    //? check if the user exists with the provided credentials
    const userExists = await User.findOne({ email: email });
    if (!userExists) {
      if (req.body.autoGenerated) {
        //? create a new account for the user attempting to log via google
        //? create and hash a password
        const pw = otp_generator.generate(12) + "!1";
        const hashed_pw = await bcrypt.hash(pw, 10);
        //? create user
        const newUser = await User({
          email: req.body.email,
          username: req.body.username,
          password: hashed_pw,
          isVerified: true,
        });
        await newUser.save();
        console.log(newUser);
        //? create authorization token
        const jwtPayload = { id: newUser._id };
        const token = await JWT.sign(jwtPayload, process.env.JWT_SECRET_KEY, {
          expiresIn: "30d",
        });

        //? no need to verify account, as user is already logging in via his socials
        //? but inform user about account creation
        const emailBody = `<p>Account created successfully ! Your password is ${pw}. Please change it!</p>`;
        const subject = `Account Created via Google Account`;
        await sendEmail(req.body.email, subject, emailBody);

        //? return authorizatio token
        res.status(200).json({ message: subject, token });
      }
      return res
        .status(400)
        .json({ message: `No user exists with this email ${email}` });
    }
    //? validate the user : account validation, password validation
    //? check account verification
    if (!userExists.isVerified) {
      return res.status(400).json({
        message: `User is not verified, Please click on the link sent to you on ${email} to verify your account`,
      });
    }
    //? check PW
    const isPwCorrect = await bcrypt.compare(password, userExists.password); // (plainTextPassword, hashedPassword)
    if (!isPwCorrect) {
      return res
        .status(400)
        .json({ message: `The password you provided is wrong` });
    }
    //? Once user credentials are approved, create JWT token
    //? payload = are the details we want to include in the token t be generated
    const jwtPayload = { id: userExists._id };
    const token = JWT.sign(jwtPayload, process.env.JWT_SECRET_KEY, {
      expiresIn: "30d",
    }); //payload, secret_key
    console.log(token);

    //? send response
    res.json({ message: "User logged in successfully", token });
  } catch (e) {
    res.json({ e });
  }
};
//! verify user
const verifyUser = async (req, res) => {
  try {
    //? check if token is valid
    const isTokenValid = await User.findOne({
      "VerificationToken.token": req.params.token,
      "VerificationToken.expires": { $gt: new Date() },
    });
    console.log(isTokenValid);
    const tok = req.params.token;
    if (!isTokenValid) {
      return res
        .status(400)
        .send(
          `<p>Token Invalid or Expired</p>` +
            `<a href=http://localhost:5000/api/v1/user/resendVerification/${tok}>Resend Verification Mail</a>`
        );
    }

    if (isTokenValid.isVerified == true) {
      return res.send("Account already verified");
    } else {
      isTokenValid.isVerified = true;
      await isTokenValid.save();
      res.send("Account verified successfully");
    }
  } catch (e) {
    console.log(e);

    return res.json(e);
  }
};
//! resend verification

const resendVerification = async (req, res) => {
  try {
    console.log("inside resend");
    const token = req.params.token;
    //? find the user in question
    const user = await User.findOne({
      "VerificationToken.token": token,
      isVerified: "false",
    });
    console.log(user);

    //? regenerate the token
    const VerificationToken = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });
    const expires = new Date();
    expires.setMinutes(expires.getMinutes() + 5); //* 5 minutes
    //? update the token within the user
    user.VerificationToken.token = VerificationToken;
    user.VerificationToken.expires = expires;
    await user.save();
    console.log(user);
    //? Resend account verification email
    const emailBody = `<p>Please click on the link to verify your account <b>http://localhost:5000/api/v1/user/verify/${VerificationToken}</b></p>`;
    const subject = `Verification Email`;
    await sendEmail(user.email, subject, emailBody);

    //? Send a response
    res.json({
      message:
        "Please check your email, a new verification link will be sent to you",
    });
  } catch (e) {
    res.json({ message: "Something went wrong" });
  }
};

//! forgot password
const forgotPassword = async (req, res) => {
  try {
    //? first check if user exists
    console.log(req.body.email);

    const userExists = await User.findOne({ email: req.body.email });
    if (!userExists) {
      return res.status(400).json({
        message: `No user with this email ${req.body.email} was found`,
      });
    }
    console.log(req.body.isOTPVerified);
    console.log(req.body.password);

    //? reset the password
    if (req.body.isOTPVerified) {
      console.log("inside verified");

      const hashedPassword = await bcrypt.hash(req.body.password, 10);
      userExists.password = hashedPassword; // hashedPassword;
      await userExists.save();
      //? send email
      const emailBody = `<p>Your password reset was successful!</p>`;
      const subject = `Password reset successfully`;
      await sendEmail(req.body.email, subject, emailBody);
      return res
        .status(200)
        .json({ message: "Password reseted successfully!" });
    }
    //? create a recent token
    const OTP = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });
    const expires = new Date();
    expires.setMinutes(expires.getMinutes() + 5);

    userExists.OTP_VerificationToken = { OTP, expires };
    await userExists.save();
    //? send email
    const emailBody = `<p>Your OTP for password request is ${OTP}. This token expires in 5 minutes!</p>`;
    const subject = `Password reset OTP`;
    await sendEmail(userExists.email, subject, emailBody);
    res.status(200).json({ message: "OTP sent, please check your email!" });
  } catch (error) {
    res
      .status(500)
      .json({ message: "Something went wrong!", email: req.body.email });
  }
};
//! verify password reset OTP
const verifyPasswordOTP = async (req, res) => {
  try {
    const recievedOTP = req.params.OTP;
    //? find the user holding this token
    const userExists = await User.findOne({
      "OTP_VerificationToken.OTP": recievedOTP,
    });
    if (!userExists) {
      return res
        .status(400)
        .json({ message: "The token you provided is wrong!" });
    }
    //? check if the token is not outdated

    if (userExists.OTP_VerificationToken.expires < new Date()) {
      return res
        .status(400)
        .json({ message: "The token you provided is expired!" });
    }
    //? otherwise everything is good
    res.status(200).json({ message: "OTP Verified successfully" });
  } catch (error) {
    return res.status(500).json({ message: "Something wrong!" });
  }
};
//! reset password
const resetPassword = (req, res) => {
  try {
  } catch (error) {}
};
//! update user
const updateUser = async (req, res) => {
  try {
    const user = req.user_id;
    res.status(201).json({ message: "inside update user", user });
  } catch (e) {
    res.status(500).json(e);
  }
};
//! get user
const getUser = async (req, res) => {
  try {
    const user_id = req.user_id;
    const userExists = await User.findById(user_id);
    const user = { email: userExists.email, username: userExists.username };
    console.log(user);

    res.status(200).json(user);
  } catch (error) {
    res.status(500).json({ message: "Something went wrong!" });
  }
};
module.exports = {
  register,
  login,
  verifyUser,
  resendVerification,
  updateUser,
  forgotPassword,
  verifyPasswordOTP,
  resetPassword,
  getUser,
};
