import React, { useState, type ChangeEvent } from "react";
import toast from "react-hot-toast";
import { passwordRegex, emailRegex } from "../../Utils/RegEx";
import styles from "./Login.module.css";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import {
  FacebookLoginButton,
  GoogleLoginButton,
} from "react-social-login-buttons";
import { useGoogleLogin } from "@react-oauth/google";

type Props = {};

function Login({}: Props) {
  const [userDetails, setUserDetails] = useState({
    password: "",
    email: "",
  });
  const navigate = useNavigate();
  const [show, setShow] = useState(false);
  //! handle values change
  const handlevaluechange = (event: ChangeEvent<HTMLInputElement>) => {
    const name = event.target.name;
    const value = event.target.value;
    setUserDetails({ ...userDetails, [name]: value });
    //console.log(userDetails);
  };

  //! handle traditional login
  const handleLogin = async () => {
    if (!emailRegex.test(userDetails.email)) {
      toast.error("Please Provide a valid email address!");
      return;
    }
    if (!passwordRegex.test(userDetails.password)) {
      toast.error(
        "Password must be at least 8 characters and must include at least one special character and one number!"
      );
      return;
    }
    //? after form validation, make a login request
    try {
      console.log("inside login");

      const response = await axios.post(
        `${import.meta.env.VITE_BASE_SERVER_URL}api/v1/user/login`,
        { email: userDetails.email, password: userDetails.password }
      );
      console.log(response.data);
      toast.success(response.data.message);
      //? store token
      localStorage.setItem("token", response.data.token);
      //? navigate successfully to home
      navigate("/home");
    } catch (e: any) {
      toast.error(e.response.data.message);
    }
  };

  //! handloe login with google
  const handleContinueWithGoogle = useGoogleLogin({
    onSuccess: async (response: any) => {
      console.log(response);
      const res = await axios.get(
        "https://www.googleapis.com/oauth2/v3/userinfo",
        {
          headers: { Authorization: `Bearer ${response.access_token}` },
        }
      );
      //console.log(res);
      //? making use of the user retrieved data to check if he either already have an account, or needs new one created!
      const newUser = {
        username: res?.data?.name,
        email: res?.data?.email,
        autoGenerated: true,
      };
      console.log(newUser);
      //? login
      try {
        const response = await axios.post(
          `${import.meta.env.VITE_BASE_SERVER_URL}api/v1/user/login`,
          newUser
        );
        console.log(response);

        toast.success(response.data.message);
        localStorage.setItem("token", response.data.token);
        navigate("/");
      } catch (e: any) {
        console.log(e);

        toast.error(e.response.data.message);
      }
    },
    onError: (error: any) => {
      console.log(error);
    },
  });

  return (
    <div className={styles.container}>
      <div className={styles.formContainer}>
        <h2>Log In ...</h2>
        <div className={styles.socials}>
          <div onClick={handleContinueWithGoogle}>
            <GoogleLoginButton />
          </div>
        </div>
        <div className={styles.inputContainer}>
          <input
            type="email"
            name="email"
            value={userDetails.email}
            placeholder="Enter your email"
            required
            onChange={handlevaluechange}
          />
          <div className={styles.passwordContainer}>
            <input
              type={show ? "text" : "password"}
              value={userDetails.password}
              name="password"
              placeholder="Enter your password"
              required
              onChange={handlevaluechange}
            />
            <button onClick={() => setShow(!show)}>
              {show ? "HIDE" : "SHOW"}
            </button>
          </div>
          <button onClick={handleLogin}>Log In</button>
        </div>

        <div className={styles.footer}>
          <Link to="/signup">Don't have an account? Sign up</Link>
          <Link to="/forgot-password">Forgot Password?</Link>
        </div>
      </div>
    </div>
  );
}

export default Login;
